# Frontend Development Dockerfile
FROM node:18-alpine

RUN apk add --no-cache libc6-compat

WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm install

COPY . .

EXPOSE 3002

ENV PORT=3002
ENV HOSTNAME "0.0.0.0"

CMD ["npm", "run", "dev"]
