#!/bin/bash
# Service detection script for monorepo
# Auto-generated by aicodepath-git-monorepo-config skill
#
# Scans the repository for services by looking for package managers
# and build files. Generates services.yaml with detected services.

set -e

PROJECT_ROOT="${1:-.}"

echo "Scanning for services in monorepo..."

# Detect repository platform
REMOTE=$(git -C "$PROJECT_ROOT" remote get-url origin 2>/dev/null || echo "")
PLATFORM="unknown"
if [[ "$REMOTE" == *"github.com"* ]]; then
    PLATFORM="github"
elif [[ "$REMOTE" == *"gitlab.com"* ]]; then
    PLATFORM="gitlab"
elif [[ "$REMOTE" == *"bitbucket.org"* ]]; then
    PLATFORM="bitbucket"
fi

# Collect services
declare -a SERVICE_NAMES
declare -a SERVICE_PATHS
declare -a SERVICE_TYPES
declare -a SERVICE_DOCKERFILES

# Look for Node.js services (package.json, excluding root and node_modules)
while IFS= read -r pkg_file; do
    [ -z "$pkg_file" ] && continue
    svc_path=$(dirname "$pkg_file")
    svc_name=$(basename "$svc_path")
    # Skip root package.json and node_modules
    if [ "$svc_path" != "." ] && [[ "$svc_path" != *"node_modules"* ]]; then
        SERVICE_NAMES+=("$svc_name")
        SERVICE_PATHS+=("$svc_path")
        SERVICE_TYPES+=("node")
        if [ -f "$svc_path/Dockerfile" ]; then
            SERVICE_DOCKERFILES+=("true")
        else
            SERVICE_DOCKERFILES+=("false")
        fi
    fi
done < <(find "$PROJECT_ROOT" -maxdepth 3 -name "package.json" -not -path "*/node_modules/*" 2>/dev/null | sed "s|^$PROJECT_ROOT/||")

# Look for Python services
while IFS= read -r req_file; do
    [ -z "$req_file" ] && continue
    svc_path=$(dirname "$req_file")
    svc_name=$(basename "$svc_path")
    if [ "$svc_path" != "." ]; then
        # Avoid duplicates
        if [[ ! " ${SERVICE_PATHS[*]} " =~ " ${svc_path} " ]]; then
            SERVICE_NAMES+=("$svc_name")
            SERVICE_PATHS+=("$svc_path")
            SERVICE_TYPES+=("python")
            if [ -f "$svc_path/Dockerfile" ]; then
                SERVICE_DOCKERFILES+=("true")
            else
                SERVICE_DOCKERFILES+=("false")
            fi
        fi
    fi
done < <(find "$PROJECT_ROOT" -maxdepth 3 \( -name "requirements.txt" -o -name "pyproject.toml" \) -not -path "*/venv/*" -not -path "*/.venv/*" 2>/dev/null | sed "s|^$PROJECT_ROOT/||")

# Look for Go services
while IFS= read -r go_file; do
    [ -z "$go_file" ] && continue
    svc_path=$(dirname "$go_file")
    svc_name=$(basename "$svc_path")
    if [ "$svc_path" != "." ]; then
        if [[ ! " ${SERVICE_PATHS[*]} " =~ " ${svc_path} " ]]; then
            SERVICE_NAMES+=("$svc_name")
            SERVICE_PATHS+=("$svc_path")
            SERVICE_TYPES+=("go")
            if [ -f "$svc_path/Dockerfile" ]; then
                SERVICE_DOCKERFILES+=("true")
            else
                SERVICE_DOCKERFILES+=("false")
            fi
        fi
    fi
done < <(find "$PROJECT_ROOT" -maxdepth 3 -name "go.mod" 2>/dev/null | sed "s|^$PROJECT_ROOT/||")

# Look for Java services
while IFS= read -r java_file; do
    [ -z "$java_file" ] && continue
    svc_path=$(dirname "$java_file")
    svc_name=$(basename "$svc_path")
    if [ "$svc_path" != "." ]; then
        if [[ ! " ${SERVICE_PATHS[*]} " =~ " ${svc_path} " ]]; then
            SERVICE_NAMES+=("$svc_name")
            SERVICE_PATHS+=("$svc_path")
            if [[ "$java_file" == *"pom.xml" ]]; then
                SERVICE_TYPES+=("java-maven")
            else
                SERVICE_TYPES+=("java-gradle")
            fi
            if [ -f "$svc_path/Dockerfile" ]; then
                SERVICE_DOCKERFILES+=("true")
            else
                SERVICE_DOCKERFILES+=("false")
            fi
        fi
    fi
done < <(find "$PROJECT_ROOT" -maxdepth 3 \( -name "pom.xml" -o -name "build.gradle" \) 2>/dev/null | sed "s|^$PROJECT_ROOT/||")

SERVICE_COUNT=${#SERVICE_NAMES[@]}

echo "Found $SERVICE_COUNT services:"
for i in "${!SERVICE_NAMES[@]}"; do
    echo "  - ${SERVICE_NAMES[$i]} (${SERVICE_TYPES[$i]}) at ${SERVICE_PATHS[$i]}"
done

# Generate services.yaml
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
OUTPUT_FILE="$PROJECT_ROOT/services.yaml"

cat > "$OUTPUT_FILE" <<EOF
# Service manifest for monorepo
# Auto-generated by aicodepath-git-monorepo-config skill
# Last updated: $TIMESTAMP

version: "1.0"

# Repository information
repository:
  platform: $PLATFORM
  branches:
    development: dev
    staging: staging
    production: main

# Detected services
services:
EOF

for i in "${!SERVICE_NAMES[@]}"; do
    cat >> "$OUTPUT_FILE" <<EOF
  - name: ${SERVICE_NAMES[$i]}
    path: ${SERVICE_PATHS[$i]}
    type: ${SERVICE_TYPES[$i]}
    has_dockerfile: ${SERVICE_DOCKERFILES[$i]}
    dependencies: []

EOF
done

cat >> "$OUTPUT_FILE" <<EOF
# Git workflow configuration
workflow:
  branch_protection:
    enabled: true
    dev:
      required_reviewers: 1
      enforce_admins: false
    staging:
      required_reviewers: 2
      enforce_admins: true
    main:
      required_reviewers: 3
      enforce_admins: true
      require_signed_commits: true

  hooks:
    pre_commit: true
    pre_push: true
    commit_msg: true

# Status tracking (for integration with gcp-monorepo-deploy)
setup_status:
  git_configured: true
  branches_created: false
  protection_rules_configured: false
  hooks_installed: false
  services_detected: true
  ready_for_deployment: false
  last_updated: $TIMESTAMP
EOF

echo ""
echo "services.yaml created at $OUTPUT_FILE"
echo "Found $SERVICE_COUNT services"
