#!/bin/bash
# Install Git hooks for team members
# Auto-generated by aicodepath-git-monorepo-config skill
#
# Creates .githooks/ directory in the project root,
# copies hook templates, and configures Git to use them.

set -e

PROJECT_ROOT="${1:-.}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEMPLATES_DIR="$SCRIPT_DIR/../templates/git-hooks"

echo "Installing Git hooks..."

# Verify we're in a git repository
if ! git -C "$PROJECT_ROOT" rev-parse --git-dir > /dev/null 2>&1; then
    echo "Error: Not a Git repository"
    exit 1
fi

# Create hooks directory
HOOKS_DIR="$PROJECT_ROOT/.githooks"
mkdir -p "$HOOKS_DIR"

# Copy hook templates
HOOKS_INSTALLED=0
for hook_file in "$TEMPLATES_DIR"/*; do
    if [ -f "$hook_file" ]; then
        hook_name=$(basename "$hook_file")
        cp "$hook_file" "$HOOKS_DIR/$hook_name"
        chmod +x "$HOOKS_DIR/$hook_name"
        echo "  Installed: $hook_name"
        HOOKS_INSTALLED=$((HOOKS_INSTALLED + 1))
    fi
done

# Configure Git to use custom hooks directory
git -C "$PROJECT_ROOT" config core.hooksPath .githooks

echo ""
echo "Git hooks installed successfully ($HOOKS_INSTALLED hooks)"
echo ""
echo "Hooks installed:"
echo "  - pre-push: Prevents accidental production pushes"
echo "  - pre-commit: Checks for debug statements and large files"
echo "  - commit-msg: Enforces conventional commit format"
echo ""
echo "To verify, try: git commit -m 'test: validate commit hooks'"
