#!/bin/bash
# Validate Git monorepo setup
# Auto-generated by aicodepath-git-monorepo-config skill
#
# Checks that all required components are in place:
# branches, hooks, services.yaml, documentation.

set -e

PROJECT_ROOT="${1:-.}"

echo "Validating Git configuration..."
echo ""

ERRORS=0
WARNINGS=0

# Check branches exist
for branch in dev staging main; do
    if git -C "$PROJECT_ROOT" show-ref --verify --quiet "refs/heads/$branch" 2>/dev/null; then
        echo "  [PASS] Branch exists: $branch"
    elif git -C "$PROJECT_ROOT" show-ref --verify --quiet "refs/remotes/origin/$branch" 2>/dev/null; then
        echo "  [PASS] Remote branch exists: origin/$branch"
    else
        echo "  [FAIL] Missing branch: $branch"
        ERRORS=$((ERRORS + 1))
    fi
done

echo ""

# Check hooks installed
if [ -d "$PROJECT_ROOT/.githooks" ]; then
    echo "  [PASS] Git hooks directory exists"

    for hook in pre-push pre-commit commit-msg; do
        if [ -x "$PROJECT_ROOT/.githooks/$hook" ]; then
            echo "  [PASS] Hook installed: $hook"
        else
            echo "  [WARN] Hook missing or not executable: $hook"
            WARNINGS=$((WARNINGS + 1))
        fi
    done

    # Check core.hooksPath is configured
    HOOKS_PATH=$(git -C "$PROJECT_ROOT" config core.hooksPath 2>/dev/null || echo "")
    if [ "$HOOKS_PATH" = ".githooks" ]; then
        echo "  [PASS] core.hooksPath configured"
    else
        echo "  [WARN] core.hooksPath not set to .githooks"
        WARNINGS=$((WARNINGS + 1))
    fi
else
    echo "  [FAIL] Git hooks directory missing"
    ERRORS=$((ERRORS + 1))
fi

echo ""

# Check service manifest
if [ -f "$PROJECT_ROOT/services.yaml" ]; then
    echo "  [PASS] services.yaml exists"
    # Check it has content
    if grep -q "^services:" "$PROJECT_ROOT/services.yaml" 2>/dev/null; then
        echo "  [PASS] services.yaml has valid structure"
    else
        echo "  [WARN] services.yaml may have invalid structure"
        WARNINGS=$((WARNINGS + 1))
    fi
else
    echo "  [FAIL] services.yaml missing"
    ERRORS=$((ERRORS + 1))
fi

echo ""

# Check documentation
if [ -f "$PROJECT_ROOT/docs/GIT_WORKFLOW.md" ]; then
    echo "  [PASS] Documentation exists"
else
    echo "  [WARN] docs/GIT_WORKFLOW.md not found"
    WARNINGS=$((WARNINGS + 1))
fi

# Check .gitattributes
if [ -f "$PROJECT_ROOT/.gitattributes" ]; then
    echo "  [PASS] .gitattributes exists"
else
    echo "  [WARN] .gitattributes not found"
    WARNINGS=$((WARNINGS + 1))
fi

# Summary
echo ""
echo "================================"
if [ "$ERRORS" -eq 0 ] && [ "$WARNINGS" -eq 0 ]; then
    echo "All validation checks passed!"
    exit 0
elif [ "$ERRORS" -eq 0 ]; then
    echo "Passed with $WARNINGS warning(s)"
    exit 0
else
    echo "Validation failed: $ERRORS error(s), $WARNINGS warning(s)"
    exit 1
fi
